<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lua</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Lua2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapes</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapes</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[(=*)\[</string>
			<key>end</key>
			<string>\]\1\]</string>
			<key>name</key>
			<string>string.quoted.other.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|break|do|else|elseif|end|for|function|if|in|local|not|or|repeat|return|then|until|while)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|nil|true)\b</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-+*/%\^#]|~=|[=&lt;&gt;]=?|\.\.\.</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([.:])\s*([A-Za-z_][A-Za-z_]*)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.lua</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\bself\b</string>
			<key>name</key>
			<string>variable.language.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_G|_VERSION|coroutine|debug|io|math|os|package|string|table|utf8)\b</string>
			<key>name</key>
			<string>support.variable.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|collectgarbage|dofile|error|[gs]etfenv|[gs]etmetatable|ipairs|load(file|string)?|module|next|pairs|x?pcall|print|raw(equal|get|len|set)|require|select|to(number|string)|type|unpack)\b</string>
			<key>name</key>
			<string>support.function.lua</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escapes</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.lua</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua2</string>
	<key>uuid</key>
	<string>E9195272-58EC-4336-A4FC-FAE58CE34EFF</string>
</dict>
</plist>
